### ISSUE TITLE
Taskbar

### ISSUE THREAD

**Issue by goeck** [priomsrb/lighttasks#1]
Nice little programm, though should vanish from taskbar when minimizing and clicking on "close" - X, same as using existing "hide" functionality. Also needs Icon in exe.

keep it up
goeck

**Comment by priomsrb** [comment]
Thanks for your feedback.

Hiding when closing seems like a good idea. Someone else asked for the same thing. I'm not 100% sure about hiding when minimizing though. I'll have a look at what other apps do and see if it's suitable or not.

The exe seems to have an icon on my machine, though it does take a few seconds to load. Did you see any icon after extracting it?

Thanks
Shafqat

**Comment by goeck** [comment]
Hey,

yeah, your concern regarding minimizing might be right. That would obviously be a straight forward way: minimize to taskbar, close to notification area. I'd be very happy with this.

I got the compiled program through the zip file from github (by the way, the link in qtapps seems to be broken, I had to searcg for the repository on github and find the zip file) without a icon after extracting the single zip file.

Hope this helps.
Cheers
goeck

**Comment by goeck** [comment]
Hey,

today when I started up the computer I saw the exe's icon appear. So it was there, but not shown until the computer was restarted, strange. Maybe the iconing stuff just has to be improved, but not reimplemented...

thanks anyways.

Also I saw, you implemented the close&hide feature, THX :-)

Cheers
goeck

**Comment by priomsrb** [comment]
Hmm. The icon not showing up intially is weird. Not sure if it's Windows' fault or mine though. I might try out the exe on other machines and see if I can reproduce it.

Also I've fixed the link in the qt-apps. That was an embarrasing error :)
